### ISSUE TITLE
`Register` function name is overused

### ISSUE THREAD

**Issue by glibsm** [uber-go/fx#432]
There are currently three usages of function `Register` which have entirely different applications:

1. `dig.Register` inserts into the dependency graph.
2. `task.Register` registers a function into the async task module, or an interface implementation.
3. `dispatcher.Register` registers `[]transport.Procedure` for YARPC.

Two out of the three are under UberFx control, one comes from YARPC. 

An earlier suggestion was to rename `dig.Register` to `dig.Provide`. I am now in favor of the change to try and break up the overloaded word.

**Comment by madhuravi** [comment]
What makes this confusing? Each function is in the context of its own package (dig/task/dispatcher), has different arguments. It should be clear to the user from context/arguments/comments what it's doing.

**Comment by breerly** [comment]
I suggest renaming `dig.Register` to `dig.Provide`.

`Provide` is much more inline with what is actually occurring: a user is providing a type or constructor to the container, so that the object graph can be built.

`Provide` is much more specific, and a better name AFAICT.

**Comment by madhuravi** [comment]
I see. Register seems that way to me - a user is registering a type or constructor with the container, so that the object graph can be built.
Another commonly used function is "Run", it is clear what it is though, makes sense that it's used frequently.
So this doesn't get missed, pasting again - What makes this confusing? Each function is in the context of its own package (dig/task/dispatcher), has different arguments. It should be clear to the user from context/arguments/comments what it's doing.

**Comment by breerly** [comment]
Closing - the `modular` branch, and soon `dev`, doesn't use the "Register" terminology in its API.
