### ISSUE TITLE
App.Done() should return <-chan struct{}

### ISSUE THREAD

**Issue by breerly** [uber-go/fx#526]
Just like [context.Context](https://golang.org/pkg/context/#pkg-examples), `App.Done()` should return a `<-chan struct{}` instead of a `<-chan os.Signals`.

This will keep Done open-ended, allowing us to change the implementation details without breaking users.

**Comment by akshayjshah** [comment]
Prototyped this on a branch - it's feasible, but introduces a fair bit of extra complexity. In order to do this, the `App` needs to run a background goroutine that reads off the signals channel and closes some `chan struct{}` to unblock main. This gets a little hairy in error cases, and makes it challenging to start and stop an app multiple times.

I don't think it's worth it. The signals package is designed to solve exactly this use case, is widely used, and - if it's absolutely necessary - we can always represent alternate sources of information as `os.Interrupt`.
