### ISSUE TITLE
What happened to the ulog package?

### ISSUE THREAD

**Issue by mhamrah** [uber-go/fx#549]
I noticed a bunch of packages were dropped (specifically ulog) from beta3 to beta4. I know uber fx is beta, but wondering if there was any guidance for those using that package and/or docs on reasons for the refactor?

Thanks

**Comment by glibsm** [comment]
Hi @mhamrah, thanks for reaching out.

You're right, Fx is still in beta and as you can tell from the changelog we went through a very large pivot between beta3 and beta4, and we didn't do a great job explaining the reasoning for *why* it was made. Hopefully the forthcoming documentation and examples will solve that issue soon.

As far as your question, `ulog` package was a temporary work-around until our logging library `go.uber.org/zap` could properly implement the "sugared interface" - the interface which allows to pass key-value pairs, rather than concrete type structs.

Essentially, as zap released a v1.0 everything in the ulog package was obsoleted and can be found directly in Zap.

If you are looking for the tracing helper that was one part of the ulog package, you can find it directly in the jaeger client now: https://github.com/uber/jaeger-client-go/blob/709b40e7ebb3b362c562122457d4980d730ec93c/log/zap/field.go#L40

**Comment by mhamrah** [comment]
Thanks for the response Glib, I was already using zap and simply using ulog
for its zap -> sentry integration. uLog had some code to bridge the zap
logger to sentry, so I could run logging with zap and get sentry support
when running internally at Uber. I guess I need to port it over myself,
unless you know if it exists anywhere else?

**Comment by akshayjshah** [comment]
@mhamrah I'll email you - the same functionality is available (and is faster too 🚀 ), but it's now an internal package.

**Comment by tshradheya** [comment]
Hey. @akshayjshah could you email it to me as well?

**Comment by akshayjshah** [comment]
@tshradheya Nope, it's now proprietary and internal to Uber. We use `go.uber.org/zap` for most application logging, which is open-source and freely available.
