### ISSUE TITLE
fx.In and fx.Out

### ISSUE THREAD

**Issue by breerly** [uber-go/fx#558]
I've came to the realization that we *should* actually re-export these types.

Users will be perplexed when they come across a `dig.In` or `dig.Out`, and it will strain our ability to write good docs (because we'll be jumping between the libs).

With `fx.In` and `fx.Out`, we'll be able to write about these features from Fx's docs, and users will draw less ?Qs? when they come across the types in the wild.

**Comment by akshayjshah** [comment]
Throughout our modules, we use `Params` and `Result` to refer to the same concepts as `In` and `Out`. What do we think about `fx.Params` and `fx.Result`? This makes it super-clear which type should be embedded where.

**Comment by breerly** [comment]
Even better - totally agreed!

**Comment by glibsm** [comment]
We started with Params/Result (which is probably why some docs still refer to them), had some conversations, and switched to In/Out.

I'm not very willing to switch, especially because I like the relationship of In/Out to the word dig.

**Comment by breerly** [comment]
@glib I hear you, but at the same time I think dig shouldn't come into our decision making process at all.

Fx is the user-facing product - Param and Result are longer but more explicit and in my opinion more obvious.

I'd rather us lean on APIs that are as clear as can be for Fx users, regardless of the underlying dig API.

Can you buy that?

**Comment by glibsm** [comment]
I find it odd that the concepts change names across repos. If I understand correctly, we're just talking about doing a new type, right?

```go
package fx

type Param dig.In
type Result dig.Out
```

If so, per @akshayjshah [earlier comment](https://github.com/uber-go/dig/pull/118#issuecomment-312375581) on `dig.Function` as a typealias for `interface{}`, what is the *behavior* being added by Param and Result that is not already covered by In/Out?

The *main* incentive for me is not the extra ability to document in the same package, but rather the fact that `fx` can fully control the `dig` version, without people having to import two.

**Comment by breerly** [comment]
re:extra behavior - I *think* the alias is all that's needed (cc @abhinav)

re: only needing to import fx - sure, and maybe also the benefit of literally not having to know about dig. I think this is a pretty big one when we think about teaching Fx, and the fact that hundreds of engineers will have to learn it.

re:in/out vs param/result - if we're naming the structs in modules param/result right now, then it must mean we think that is the most obvious name for these types. I don't see why the aliases wouldnt compliment that.

**Comment by glibsm** [comment]
I think this conversation is starting to fragment a little bit. Lets split this up into a couple of separate topics.

## A: dig.In vs dig.Out (unrelated to Fx)

This is what I initially thought we were talking about. It sounds like we currently don't plan any changes to the dig's actual naming of these types.

## B: fx.Param and fx.Result

I like that this lets us control the dig version under the hood and hide it from the service. What I *DO NOT* like about it is that this introduces yet more names. 

What my gut is telling me to do is to consolidate: either do In/Out or Param/Result in both places. I would want to strive for consistency.

## C: Meta: hiding people form dig

I do not think this should be a target of ours. There are dig-specific components that come into play even when using Fx:

- how pointers and interfaces are handled
- how value types are handled
- what happens if you want an optional parameter
- etc

Do we plan to double-document it in both places? It sounds like completely shielding from dig is going to be difficult. I have flashbacks to ulog, when we were trying to hide zap.

**Comment by breerly** [comment]
Lets meet in person, I dont see us coming to a consensus here.

**Comment by glibsm** [comment]
### Rename

For the time being we decided to table the rename discussion (result vs out), and just focus on exporting package level concepts from Fx that will allow consumers not to directly rely on dig.

## "Aliasing" to fx.In

### Reasoning

Two major reasons for doing so:
1. It will allow all the documentation to live in a single package, without jumping to and from dig
2. It will allow fx to control the dig version. This will allow Fx to stand the test of time better, even if dig migrates major versions.

### Execution

Dig does checking on embedded `dig.In` and `dig.Out` types to fork the behavior from operating directly on the type, to operate on the struct fields instead.

Unfortunately, the go 1.9 rename is not yet here and doing `type In dig.In` is not an option, as I believe it would break the dig logic. It is still an option that should be attempted, but I do not expect it to work.

We should, however, be able to do the following:

```go
package fx
type In struct {
  dig.In
}
```

Since dig does checking as a BFS of all the embedded struct types, this should continue to work. Of course, a PR with sufficient unit testing will reveal the true answer.

**Comment by abhinav** [comment]
`type In struct{ dig.In }` will definitely work. The BFS was implemented for
that reason (plus to support `reflect.StructOf`-generated structs).
