### ISSUE TITLE
Inject doesn't respect named types

### ISSUE THREAD

**Issue by bayesianmind** [uber-go/fx#564]
fx.Inject silently strips named and optional dig tags from structs you try to inject with it. This is surprising behavior.
If you know how it works by generating a series of invokes than it makes sense but users are likely to get confused by this.

# Option 1: Better error message but no functional change
We should at the very least warn users if they have named or optional tags on their inject

# Option 2: If Inject is called with struct implementing dig.In then respect the tags
If the input struct is a dig.In type than rather than generating a 'fanned out' constructor with all members of the struct as params, just generate a constructor with the input struct directly. That should fix both optionals and named types in one go.

**Comment by glibsm** [comment]
Going to look into this.

Are you saying that if i inject with an optional that's not in the graph I will get an error?

**Comment by bayesianmind** [comment]
Yes that's right. One fix would be if the input struct is a dig.In type than rather than generating a 'fanned out' constructor, just generate a constructor with the input struct directly. That should fix both optionals and named types in one go.

**Comment by akshayjshah** [comment]
This is an artifact of `dig.In` and `dig.Out` being interfaces when `Inject` was written. We should be able to fix this by building a params struct in `Inject` instead of a function.

**Comment by bayesianmind** [comment]
Does dig recursively walk dig.In structs and do the right thing if one of the members is also a dig.In struct?

**Comment by akshayjshah** [comment]
Yep!

**Comment by abhinav** [comment]
Hey, this is totally doable. The original implementation of Inject didn't do this because at the time, `dig.In` was implemented in a way where structs generated with `reflect.StructOf` could not be `dig.In` structs. So the function it generates is,

    func(field1, field2, ...) { .. }

We can now change that to,

    func(struct{dig.In; Field1; Field2}) { .. }

@bayesianmind has already written some code in https://github.com/yarpc/yarpc-go/pull/1200 which uses reflection to generate dig.In structs.

That said, I don't see this as a blocker for 1.0. It's a strict superset of the functionality currently offered.

**Comment by breerly** [comment]
I see no reason not to try and get it into v1.0.0 to be on the safe side.

**Comment by breerly** [comment]
E.g. It's nice to have the freedom to break things if that's what's best. Just a time opportunity thing.

**Comment by abhinav** [comment]
👍  On it
