### ISSUE TITLE
Clean up logging debt

### ISSUE THREAD

**Issue by breerly** [uber-go/fx#570]
The reflection introduced in the logging facility should be cleaned in favor of dig either doing some portion of the logging, or exposing the reflected types in a way that it doesn't need to be duplicated in a higher level.

Either way, we should get ahead of this since it might impact dig's APIs.

**Comment by glibsm** [comment]
Yep, agreed. I started this work this week and *should* have something to show in a day or two.

**Comment by breerly** [comment]
@glibsm need help with this? I think we need to see something EOD if we're going to get it in by tomorrow.

**Comment by glibsm** [comment]
@breerly We talked about this at length today. The TLDR is that we're going to punt on this work until after v1, as it has large implications on new API surface.

I have a purely-additive local prototype which we can use for Provide/Invoke notifications, but it has to introduce a lot of new API surface in order to start exposing some of the internals.

I might do some work and push a WIP/prototype branch so we can get the conversation going, but I'm fairly comfortable doing this post-v1 as well.

**Comment by breerly** [comment]
Worst case scenario is we release dig v2.0 transparently to Fx users.

Removing from v1.0.0 mileston.

**Comment by akshayjshah** [comment]
dig and fx have diverged on this already; closing since we don't have any concrete plans to do this.
