### ISSUE TITLE
Can it resolve an interface function param?

### ISSUE THREAD

**Issue by DenisNeustroev** [uber-go/fx#608]
Like this:
```go
type Repository struct {}
func (r *Repository) Fetch() {}

func NewRepository() *Repository {}

type IRepository interface {
    Fetch()
}

func NewService(r IRepository) *Service {}

app := fx.New(
    fx.Provide(
        NewRepository,
        NewService,
    ),
    fx.Invoke(func (s *Service) {
        s.Start()
    ),
)

app.Start()
```

 But I got the error: type IRepository is not in the container, did you mean to use *Repository?

**Comment by abhinav** [comment]
Hello.

Resolving interfaces is supported but the interface type must be mentioned
explicitly by the constructor (at least at this time).

So this should work if you change NewRepository to,

```go
func NewRepository() IRepository {
    return &Repository{..}
}
```

That advice does go against the recommended pattern in Go of returning structs
and accepting interfaces in scenarios like this, so another option is to keep
NewRepository as-is, but introduce the following in your fx.Provide.

```go
fx.Provide(
    NewRepository,

    // Use *Repository for IRepository.
    func(r *Repository) IRepository { return r },

    NewService,
)
```

We chose not to do this automatically because Go interfaces are implicit.
Types may end up satisfying interfaces that the author did not mean to use
them for. That said, if we can figure out a clean way to expose auto-casting,
we fully intend to support it.

**Comment by DenisNeustroev** [comment]
Thanks for the detailed answer. As you advised I wrote a converter function for casting pointers to interfaces. Works like a charm.

**Comment by glibsm** [comment]
Great to hear that! Resolving based on previous comment.
Please file more issues if you encounter them, we're always looking to make Fx better.
