### ISSUE TITLE
Allow cycle dependencies

### ISSUE THREAD

**Issue by arzonus** [uber-go/fx#618]
Hi, guys. 

We have some problems with controlling dependencies in our project and want to use fx for controlling. But we have found one some problem, fx doesn't allow cycle dependencies. 

I understand why fx doesn't allow, but maybe we can lazy call for some dependencies if fx detected a cycle of dependencies? 

```go
services/user.go
type ServiceParams struct {
  fx.In

  PlatformService services.IPlatformService `cycle:"allow"`
}

type Service struct {
  ServiceParams
}

func New(params ServiceParams) IUserService {
  return &Service{
    params,
  }
}


services/platform.go
type ServiceParams struct {
  fx.In

  UserService services.IUserService  `cycle:"allow"`
}

type Service struct {
  ServiceParams
}

func New(params ServiceParams) IPlatformService {
  return &Service{
    params,
  }
}


interfaces/services/user.go
type IUserService interface {
  
}

interfaces/services/platform.go
type IPlatformService interface {
  
}
```

In the project, we use singletons and call dependencies by a function like this:

```go
services/user/service.go
type ServiceContainer interface {
  IPlatformService() services.IPlatformService
}

type Service struct {
  ServiceParams
}

func New(params ServiceContainer) IUserService {
  return &Service{
    params,
  }
}


services/platform/service.go
type ServiceContainer interface {
  IUserService() services.IUserService
}

type Service struct {
  ServiceParams
}

func New(params ServiceContainer) IPlatformService {
  return &Service{
    params,
  }
}


interfaces/services/user.go
type IUserService interface {
  
}

interfaces/services/platform.go
type IPlatformService interface {
  
}


containers/services.go

type Container struct {
  UserService services.IUserService
  PlatformService services.IPlatformService
}

func (c *Container) IUserService() services.IUserService {
  if c.UserService != nil {
    c.UserService user.New(c)
  }
  return c.UserService
}

func (c *Container) IPlatformService() services.IPlatformService {
  if c.PlatformService != nil {
    c.PlatformService platform.New(c)
  }
  return c.PlatformService
}
```

Or maybe you can advise, what can we do it with cycle dependencies? 

Thanks

**Comment by akshayjshah** [comment]
As a general rule, we specifically wanted to avoid handling cyclic dependencies: it doesn't just make the graph resolution code more complex, it also breaks the lifecycle contract. Today, if you register lifecycle hooks in a constructor, you're guaranteed that your startup hooks execute after your dependencies'. Similarly, you're guaranteed that your shutdown hooks execute before your dependencies'. Automatically calling some constructors lazily voids this guarantee, since it's impossible to have a startup order that's both obvious and stable. Fixing this would require breaking the API of the lifecycle interface.

In general, DI containers usually solve this with setter injection. With this approach, you break dependency cycles by injecting some dependencies *after* construction, via a setter method. For example, if you have

```
func NewFoo(b *Bar) *Foo { ... }
func NewBar(f *Foo) *Bar { ... }
```

you'd break this cycle by refactoring `NewBar`:

```
type Bar struct {
  f *Foo
}

func NewBar() *Bar { return &Bar{} }

func (b *Bar) SetFoo(f *Foo) { b.f = f }
```

Then you'd call `SetFoo` in an invoked function:

```
fx.Invoke(func(f *Foo, b *Bar) {
  b.SetFoo(f)
})
```

Note that you'll have to make sure that `Bar`'s methods are safe to call when the `*Foo` field is nil.

In the (hopefully) rare situations where you absolutely can't refactor your dependency graph to remove cycles, this is a simple pattern to resolve the issue. Since cyclic dependencies are usually a code smell, we'd prefer to lean on this pattern rather than making Fx itself more complex.

**Comment by arzonus** [comment]
Thanks for the answer. 

Ok, this solution looks well, when we use simple structures and don't use interfaces. Why do I have to create a method in an interface, which doesn't belong to a functionality of the interface? Also, we can have complex business logic, when many services can cycle depends on another service, or I have to spend much time for refactoring... for what? for a possibility of a run app?
I don't agree with your opinion about graph resolution code will more complex. 

We can check every cycle dependencies, return nil interface, save reflect.Value of interface to map, and after graph initialization, change a value of reflect.Value in every struct, which depends on the interface/structure.

**Comment by akshayjshah** [comment]
You're missing the point about lifecycle hooks, which is the majority of the problem. Startup and shutdown don't work unless there's a constructor ordering that's predictable and stable.

**Comment by arzonus** [comment]
I suggest add the logic in fx.New method, in dig.Invoke, not in fx.App.Start . We can ignore values, which has marked "cycle". Behavior looks like "option" tag.

**Comment by saefullohmaslul** [comment]
Hi, I found alternative solution. On my code, both service and logger each depend

```go
func NewService(repository repositories.Repository, logger Logger) Service {
	return &ServiceImpl{
		repository: repository,
		logger:     logger,
	}
}

func NewLogger(repository repositories.Repository) Logger {
	return &LoggerImpl{
		repository: repository,
	}
}

var Module = fx.Options(
	fx.Provide(NewService),
	fx.Provide(NewLogger),
	fx.Invoke(cycle),
)

func cycle(lifecycle fx.Lifecycle, logger Logger, service Service) {
	lifecycle.Append(
		fx.Hook{
			OnStart: func(context.Context) error {
				logger.SetService(service)
				return nil
			},
		},
	)
}
```
