### ISSUE TITLE
need some help with using fx for webapp

### ISSUE THREAD

**Issue by rubensayshi** [uber-go/fx#648]
I've been spending the last few hours on trying to figure out how to use dig/fx for a webapp but the example doesn't really illustrate that well how a real webapp would look like, so I figured I'd give it a shot to just ask for help ;-)

What I'm trying to achieve is to easily inject some services into my "controllers" (http handlers), but I can't seem to figure out a way that doesn't feel right.

Are there any other resources or example projects that could help me out?

below is my best attempt so far, what I however don't really like is that I need to create MyModule with all the deps that any of my handlers need.

I tried simply using `dig` as well, but because you can't Invoke with args it doesn't seem possible to do `canWeBooyaa(rw http.ResponseWriter, r *http.Request, myService *MyService)` and then invoking that.

```go
package main

import (
	"fmt"
	"net/http"

	"go.uber.org/fx"
)

var FxModule = fx.Options(
	fx.Provide(
		NewMyModule,
		NewMyService,
	),
	fx.Invoke(
		RegisterMyModule,
	),
)

// my super complicated service
type MyService struct {
	Booyaa bool
}

// provide for my super complicated service
func NewMyService() *MyService {
	return &MyService{}
}

// register module on the mux
func RegisterMyModule(mux *http.ServeMux, myModule *MyModule) {
	mux.Handle("/mymodule/booyaa", http.HandlerFunc(myModule.canWeBooyaa))
}

// my module struct, that we just have to gather all the deps we need
type MyModule struct {
	myService *MyService
}

func NewMyModule(myService *MyService) *MyModule {
	return &MyModule{
		myService: myService,
	}
}

// our actual "controller" aka handler
func (m *MyModule) canWeBooyaa(rw http.ResponseWriter, r *http.Request) {
	rw.Write([]byte(fmt.Sprintf("booyaa? %v! \n", m.myService.Booyaa)))
}
```

**Comment by abhinav** [comment]
Hello! Thanks for your interest in Fx. Based on what I can infer about your
use case from the code, your usage is largely correct. It's hard to give a
better recommendation without a clearer idea of the use case.

That said, I'll try to summarize the idea behind Fx quickly: Fx is meant to
instantiate objects scoped to the application's lifecycle rather than those
scoped to a single request. The idea is to enable building separate decoupled
components in an application (rather than using globals), declare dependencies
on them with your constructor, and use them like they were instantiated and
provided from your `main()` by hand. In the example above, canWeBooyaa is
scoped to a single request so it won't be touched by Fx. The object that
implements canWeBooyaa is scoped to the application, so it will be touched by
Fx.

Unfortunately, our documentation around using bare Fx and other samples is a
bit lacking right now. We intend to remedy that and possibly provide some
reusable modules in the near future.

**Comment by glibsm** [comment]
I hope that I understood the question correctly. Pasted below is an example of how you can achieve what I think you're trying to do by using [value groups](https://godoc.org/go.uber.org/fx#hdr-Value_Groups).

All services take in a mux and register whatever routes they would like to handle through their constructors. The "secret sauce" is the `StartServer` invoke, which accepts as one of the parameters the value group of `[]Service`, which in turn causes dig to hunt down all the constructors that provide a `Service` and instantiate them.

We are using something similar for an internal RPC module that has to register it's handlers. As mentioned above, public documentation and sample modules are lacking. Not by design, but due to the lack of resources. Help is always appreciated!

```go
package main

import (
	"fmt"
	"net/http"
	"strings"

	"go.uber.org/fx"
)

func main() {
	fx.New(
		fx.Provide(
			NewMyService,
			// other service constructors can go here...
			http.NewServeMux,
		),
		fx.Invoke(
			StartServer,
		),
	).Run()
}

// Service is the common interface
type Service interface {
	Name() string
}

type AllServices struct {
	// special fx.In embed. See https://godoc.org/go.uber.org/fx#In
	fx.In

	// see https://godoc.org/go.uber.org/fx#hdr-Value_Groups
	// this will collect all the services from all fx.Provides
	Services []Service `group:"services"`
}

func StartServer(s AllServices, mux *http.ServeMux) {
	names := []string{}
	for _, s := range s.Services {
		names = append(names, s.Name())
	}

	fmt.Printf(
		"Starting HTTP with %d service(s): %v\n",
		len(s.Services), strings.Join(names, ","),
	)

	http.ListenAndServe(":8080", mux)
}

// my super complicated service
type BooyaaService struct {
	Booyaa bool
}

// our actual "controller" aka handler
func (s *BooyaaService) canWeBooyaa(rw http.ResponseWriter, r *http.Request) {
	rw.Write([]byte(fmt.Sprintf("booyaa? %v! \n", s.Booyaa)))
}

// Name implements the Service interface
func (s *BooyaaService) Name() string {
	return "Booyaa service"
}

type AddService struct {
	// special fx.Out embed. See https://godoc.org/go.uber.org/fx#Out
	fx.Out

	// see https://godoc.org/go.uber.org/fx#hdr-Value_Groups
	// this will append another service to the group
	Service Service `group:"services"`
}

// provide for my super complicated service
func NewMyService(mux *http.ServeMux) AddService {
	// create service
	s := &BooyaaService{Booyaa: true}

	// register all routes and handlers
	mux.Handle("/mymodule/booyaa", http.HandlerFunc(s.canWeBooyaa))

	// return the new service, and append to the services group
	return AddService{
		Service: s,
	}
}
```

**Comment by rubensayshi** [comment]
@abhinav thx, I actually do want to use it for long running services and not for per request stuff, but I want to make it easy to inject dependencies into my http handler functions when they need it.

I guess it's more "correct" to have them injected into the module and I should just deal with the boilerplate code.

@glibsm thx for the hint at the value groups, I'll take a look into those and see if they can make my lifea bit easier.
