### ISSUE TITLE
Value groups feature doesn't work with an interface 

### ISSUE THREAD

**Issue by kopaygorodsky** [uber-go/fx#650]
I'm trying to get a group of handlers for my echo server. Each handler implements Handler interface. 

Here is a container. `peer.New` is a handler constructor. 
```
func buildContainer() *fx.App {
	app := fx.New(
		fx.Provide(
			NewLogger,
			func () (*kubernetes.Clientset, error) {
				return NewKubernetesClient(viper.GetString("kubernetes.config"))
			},
			peer.New,
		),

		fx.Invoke(InitServer),
	)
	return app
}
```

Parameter struct that I pass to the server init function
```
type ServerParams struct {
	fx.In
	Handlers []server.Handler `group:"default"`
}
```

init function 

```
func InitServer(lifecycle fx.Lifecycle, params ServerParams, logger *log.Logger) {
	srv := echo.New()
	srv.Use(middleware.Logger(logger))
	apiGroup := srv.Group("/api/v1/")

       // params.Handlers has len 0, should be 1  because one handler is provided (`peer.New`)
	for _, handler := range params.Handlers {
		handler.RegisterEndpoints(apiGroup)
	}

	for _, route := range srv.Routes() {
		logger.Info(route.Path)
	}

	lifecycle.Append(fx.Hook{
		OnStart: func(ctx context.Context) error {
			go func () {
				logger.Fatal(srv.Start(":8000"))
			}()
			return nil
		},
		OnStop: func(ctx context.Context) error {
			return srv.Close()
		},
	})
}
```

I even tried to specify an explicit type for the group instead of an interface, but no luck, `peer.New` constructor never gets called.
What could be wrong?

**Comment by glibsm** [comment]
Could you show us the `peer.New` function? You can obfuscate things, but the return out of that function is really important to get the groups to work correctly.

**Comment by glibsm** [comment]
In order to consume the value groups, fx needs to be signaled what kind of types to actually group together. For that, the reverse of `fx.In` is used - `fx.Out`.

You can find the docs here https://godoc.org/go.uber.org/fx#hdr-Value_Groups.

Essentially, the `fx.Out` is needed because fx/dig do not allow more than one type without added qualifiers (name or group). The way those qualifiers get attached to the constructors is through the use of special `fx.Out` construct.

In your example, you would end up with something like this:

```
type AddPeer struct {
	fx.Out

	Handler Handler `group:"default"`
```

```
func New(kubClient *kubernetes.Clientset) AddHandler {
	return AddHandler{Handler: &Peer{kubClient:kubClient}}
}
```

This allows you to create other constructors that return `AddHander` that will all be grouped into `[]Handlers` group.

**Comment by kopaygorodsky** [comment]
oh, thx, I saw such a solution before, thought `fx.Out` has just opposite purpose and shouldn't be used together to get value groups.
I think the issue can be closed.
