### ISSUE TITLE
Option to not cache constructor values

### ISSUE THREAD

**Issue by tallpants** [uber-go/fx#661]
What the title says, basically -- is there currently any way (either built in or a common pattern) to not cache the results of the constructors given to `fx.Provide()` and instead have it instantiate a new copy by calling the constructor every time it's required?

**Comment by abhinav** [comment]
Hello! Sorry, no, there is no support for this and we don't think it's a good
idea to add it because it goes against how Fx is intended to be used.

Fx is intended to be used to manage objects for your application that are
scoped to your application's lifetime. These objects are constructed once when
your application starts up and destroyed when your application shuts down.
We are able to justify the cost of using reflection in Fx because when used
like this, the cost is paid once upfront at startup and then your application
functions as usual.

Supporting multiple instantiations would mislead users into thinking that Fx
should be used on a hot path like request processing. This is also one of the
reasons why it is not possible to specify additional provides or invokes
outside of `fx.New`.

**Comment by tallpants** [comment]
I didn't consider the runtime cost -- maybe it's worth documenting it? Anyway thanks for clearing that up!

**Comment by glibsm** [comment]
*insert slowpoke meme*

Catching up on the activity after being away for a bit.

@tallpants +1 to everything @abhinav had said. It's a good point that it should be clearly documented, I suppose this concept has just became second nature to us and we don't really think about it anymore (I believe at one point it was clearly stated that value will be reused).

There are, of course, use cases for creating a new object each time. In that case it's very convenient to have a shared factory in the container, capable of spawning new items as needed. Or even a step further if consumption is high, do an object pool with objects that can be reset back to their initial state (ala bytes.Buffer).
