### ISSUE TITLE
Formatted logger

### ISSUE THREAD

**Issue by DAddYE** [uber-go/fx#73]
I'd suggest to add the `f` variants of the logger.

```go
log.Infof("hello %v", world)
```

or find a way to make this possible in k:v

```go
log.Infof("debug", "world %+v", foo, "bar %q", bar) 
```

**Comment by sectioneight** [comment]
This is an intentional design decision of Zap for performance reasons. cc @akshayjshah @prashantv

**Comment by DAddYE** [comment]
How do we handle then:

```go
log.Error(err)
```

or 

```go
if err := ...; err != nil {
  log.Fatal(err)
}
```

**Comment by akshayjshah** [comment]
Hey David - you're right to point out that this is a bit annoying in context that aren't performance-sensitive.

The core zap logger is definitely optimized for performance over brevity, so it doesn't support string formatting. This is partly a performance issue (the `fmt` package's string formatting is slower than zap's JSON encoder), but mostly because supporting variadic formatting arguments precludes supporting a variadic number of structured fields...and that API change makes it annoying to avoid allocations. Using the core `zap.Logger`, `log.Error(err)` *could* be `log.Error(err.Error())`. Better yet, it would be `log.Error("Failed to call ServiceFoo.", zap.Error(err))`.

*However*, this is annoying if you're working in a context where a few milliseconds don't matter much. In that case, we're finishing up an wrapper around the core logger that takes an approach similar to the second option you outlined - you'd do `log.Info("Some message.", "firstField", firstField, "secondField", secondField)`.

**Comment by DAddYE** [comment]
@akshayjshah makes sense for zap not so sure about uberfx. @sectioneight shouldn't we introduce back the interpolation and allow errors in log.Fatal and log.Error (with some special handling for https://github.com/pkg/errors):

I'm pretty sure folks expect this:

```go
log.Fatal(err)
log.Error(err)
```

to work.

**Comment by sectioneight** [comment]
We can certainly provide some more convenience wrappers. cc Anup

**Comment by anuptalwalkar** [comment]
David, yes, we can provide convenient api for error logging. There are two use case around providing error log`log.Error(err)` or `log.Error("message", "error", err)` format. We just went with the later conforming with zap's interface. 
We can certainly switch back to  using `log.Error(err)`. If user wants to inject message in error log they can use `log.Error(errors.Wrap("message", err))`, etc.

GFM-213

**Comment by DAddYE** [comment]
> We can certainly switch back to using log.Error(err). If user wants to inject message in error log they can use log.Error(errors.Wrap("message", err)), etc.

Error handling is something I'd like to improve a lot in my services.

I'd probably add something like:

```go
f, err := file.Open(name)
if err != nil {
   log.ErrorWithMessage(err, "while opening file")
   // or
   log.ErrorWithStack(err) // either use pkg/errors or just add the runtime.Callers(1) to avoid an extra dependenct
   // or
   log.Error(err)
}
```

same for `Fatal`

**Comment by sectioneight** [comment]
Thanks Davide, this feedback is super helpful.

**Comment by akshayjshah** [comment]
It's probably easier to discuss code instead of little snippets. The third-party contributor who started implementing the high-level logger in zap seems to have abandoned that PR, so I've commandeered it - see uber-go/zap#185.

I think that it addresses most of the use cases here. It doesn't include explicit support for github.com/pkg/errors, though I'm happy to add that if we all think it's necessary.

**Comment by madhuravi** [comment]
+1 on have convenience wrappers in uberfx.

**Comment by DAddYE** [comment]
I do agree as well we should port the sugar here.

**Comment by peter-edge** [comment]
Is this fixed now? There should be access to the sugared logger now.

**Comment by akshayjshah** [comment]
Yep, this should be resolved.
