### ISSUE TITLE
Lazy loading inside an Fx application

### ISSUE THREAD

**Issue by EldarKurbanov** [uber-go/fx#732]
Hi! I'm prepared some spaghetti code here: https://play.golang.com/p/gZBAKyC-icZ
My question on 43 line.

I want to create a server (using GRPC) that lazily loads its dependencies. For example, the server just starts GRPC serve, and listens on the port. If the server receives a request, then the server has to load the dependencies of that request (I don't want to load dependencies at the beginning of the program, I want load them when needed).

Is that possible with Fx?

**Comment by abhinav** [comment]
Hi! No, sorry that's not possible with Fx.

Because Fx operates with use of reflection,
we suggest you use Fx only at startup, not on the request path.
We've intentionally designed most of the APIs of Fx in such a way that
using it on the request path would be inconvenient or difficult.

Closing because answered.
