### ISSUE TITLE
Question: Way to avoid boilerplate code for trivial constructors?

### ISSUE THREAD

**Issue by grantwwu** [uber-go/fx#764]
Hello 👋 

I have an service where we have to make a bunch of structs that have really trivial constructors. Namely, all they do is store the parameters wholesale. For example:

```golang
type Foo struct {
    MyBar  Bar
    MyBaz  Baz
    MyQuux Quux
}


func NewFoo(mbr Bar, mbz Baz, mq Quux) Foo {
    return Foo{
        MyBar: mbr,
        MyBaz: mbz,
        MyQuux: mq,
    }
}
```
The `Bar`, `Baz`, and `Quux` are all `fx.Provide`'d elsewhere. I have a bunch of structs that look like this, that take various combinations of these dependencies.

Is there a standard way of avoiding all this boilerplate?

I did try this:

```golang

type FooParams struct {
    fx.In
    Foo
}
type Foo struct {
    MyBar  Bar
    MyBaz  Baz
    MyQuux Quux
}


func NewFoo(fp FooParams) Foo {
    return fp.Foo
}
```

in the hopes that Fx would not see the Foo member and only see the MyBar, MyBaz, and MyQuux members embedded, but Fx was not tricked and declared that there was a circular dependency.

**Comment by prashantv** [comment]
I have seen cases where the `Foo` struct embeds `fx.In` directly,
```go
type Foo struct {
    fx.In

    MyBar  Bar
    MyBaz  Baz
    MyQuux Quux
}
```

That should work for structs where all exported fields can be provided by the Fx graph.

**Comment by chrisirhc** [comment]
I have a similar question to this.
In the unit tests for say a `Controller`, I'd like to mock out these dependencies and do something like.

I see boilerplate like:
```go
// controller.go
type Params struct {
    fx.In

    MyBar  Bar
    MyBaz  Baz
    MyQuux Quux
}

func New(p Params) (Controller) {
…
}

// controller_test.go
func TestController(t…) {
	var c Controller
	opts := fx.Options(
		fx.Provide(func() Bar {
			return …
		}),
		fx.Provide(func() Baz {
			return …
		}),
		fx.Provide(func() Quux {
			return …
		}),
		fx.Provide(New),
		fx.Populate(&c),
	)
	fxtest.New(t, opts)

	…
}

// OR
func TestControllerAlt(t…) {
	controller, _ = New(Params{
		MyBar:       …,
		MyBaz:       …,
		MyQuux:       …,
	})
	…
}

```

The nice thing about `TestController` over `TestControllerAlt` is that you get immediate feedback from fx that certain dependencies aren't fulfilled and you have a lot of control over defining fine-grained dependencies.

But is there an alternative where I can do:

```go
		fx.Provide(func() Params {
			return Params{
				MyBar:       …,
				MyBaz:       …,
				MyQuux:       …,
			}
		}),
```

This would have the best of both worlds. Succinct fx.Provide, reusing the Params object defined in the Controller.
If I tried this today, fxtest would error out with `bad result 1: cannot provide parameter objects: ….Params embeds a dig.In`.

That's because the Params struct can either have a `fx.In` or `fx.Out`. Since there's no support for embedded structs, I can't do the following which seems more concise:

```golang
type Params struct {
    MyBar  Bar
    MyBaz  Baz
    MyQuux Quux
}
func New(p struct {
	fx.In
	Params
}) (Controller, error) {
	…
}

// controller_test.go
func TestController(t…) {
	var c Controller
	type OutParams struct {
		fx.Out
		Params
	}
	opts := fx.Options(
		fx.Provide(func() OutParams {
			return OutParams{
				Params: Params{
					MyBar:       …
					MyBaz:       …
					MyQuux:       …
				},
			}
		}),
		fx.Provide(New),
		fx.Populate(&c),
	)
	fxtest.New(t, opts)

	…
}

```

**Comment by grantwwu** [comment]
Prashant, thanks for the answer, that was very helpful. Chris I didn't fully read your comment but glad to see you got it working :sweat_smile: 

Going to close this to keep the open issues count down, but definitely bookmarking this for the future.
