### ISSUE TITLE
Reducing the amount of providers on a constructor ?

### ISSUE THREAD

**Issue by iangregsondev** [uber-go/fx#823]
Hi,

I am having to inject around 9 dependencies into a constructor function, there is no way round it.

I was wondering if it's possible to inject a collection of dependencies rather than injecting each one separately ?

I would still need to store each dependency into my Struct via my constructor but it would be great to reduce the long constructor signature.

Is this something that is supported ?

Or anybody know of an alternative

**Comment by abhinav** [comment]
Hello! Yes, we have a solution for this! You can use [parameter structs](https://pkg.go.dev/go.uber.org/fx#hdr-Parameter_Structs). Basically, you embed `fx.In` in a struct, and then all **exported** fields of that struct are treated as parameters.

```go
type Params struct {
  fx.In

  Foo *Foo
  Bar *Bar
  // ..
}

func New(p Params) *Thing { ... }
```

This is equivalent to,

```go
func New(foo *Foo, bar *Bar, /* ... */) *Thing { ... }
```

Internally, we use parameter structs for nearly all our Fx modules.

Hope this helps!

(Closing because answered. Feel free to re-open or create a new ticket. Thanks!)

**Comment by iangregsondev** [comment]
Thanks! Exactly what I was looking for. Cheers.
